### ISSUE TITLE
Add Trinity and py-solc-x in setup.py

### ISSUE THREAD

**Issue by uivlis** [humanprotocol/hmt-escrow#229]
It's inconvenient to have them as build tools in every repo where we use hmt-escrow, so let's add them in setup.py as soon as the last commit from August is released on PyPi for each of them.

**Comment by excerebrose** [comment]
@uivlis Did we finish this?

**Comment by uivlis** [comment]
No, there is still no trinity PyPi release with the modifications present in the git version we use.
