### ISSUE TITLE
[Update] Outdated Docs

### ISSUE THREAD

**Issue by molecula451** [humanprotocol/hmt-escrow#277]
Docs seems to be lacking proper up to date info

![Screenshot from 2021-10-09 14-16-26](https://user-images.githubusercontent.com/41552663/136669850-ff0a7f32-dbd4-4692-b8ab-60d31f5c5884.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200560623420491/1201175416679201) by [Unito](https://www.unito.io)

**Comment by posix4e** [comment]
Tell me more, why is this incomplete? Closing for now
