### ISSUE TITLE
Get Polygon maintainer

### ISSUE THREAD

**Issue by posix4e** [humanprotocol/hmt-escrow#300]
* [ ] Launch Fortune (https://github.com/humanprotocol/fortune) on Polygon
* [ ] Verify the scanner on polygon is correct
* [ ] Verify the location of the polygon smart contracts

**Comment by vkomodey** [comment]
HMT contract "owner"(actually, they owns Proxy) - is Polygon team. @AmrEssamSh is trying to reach them. but still no luck, they just ignore his requests, unfortunately

> Verify the scanner on polygon is correct

Scanner - polygonscan.com or dashboard.humanprotocol.org?

> Verify the location of the polygon smart contracts

This is already done. We deployed factory, KV store. HMT deployed by Polygon team a while ago. Maybe I missing something?
