### ISSUE TITLE
Create and publish contracts on NPM package

### ISSUE THREAD

**Issue by Charlie85270** [humanprotocol/hmt-escrow#331]
To automate the compilation of contracts on the subgraph rpo, it is necessary to publish a npm package at each modification of the contracts, containing the last version of them.

**Comment by Charlie85270** [comment]
@posix4e

**Comment by vkomodey** [comment]
Hey, @Charlie85270. Thanks for your suggestion!

Just wondering, why do we need an npm package for a python library?
This is a python package that is published to the PyPI after each change, not only after contract changes. This library doesn’t have javascript interface also, only a python one. We use JS just for tooling(compiling, testing and etc.)

The subgraph recompilation can be done during the CD process of this package

**Comment by Charlie85270** [comment]
Hey @vkomodey, the goal is to be able to compile the contracts (Escrow.sol, EscrowFactory.sol, HMToken.sol) and generate ABI files from the subgraph repo without the need to copy them by hand each time and always have the latest version of the ABI files on the subgraph repo. 
In case of one of these contracts are updated we need two things : 

- Update the ABI files on the subgraph
- Recompile the subgraph with the new ABI files

If these two steps can be done during the CD process indeed we don't need to publish a npm package

**Comment by vkomodey** [comment]
@Charlie85270 agree!

**Comment by vkomodey** [comment]
Closed. See the #333 for further work
