### ISSUE TITLE
Integrate The Graph index engine

### ISSUE THREAD

**Issue by vkomodey** [humanprotocol/hmt-escrow#333]
**Is your feature request related to a problem? Please describe.**
It is too hard to iterate over events for a particular contract. For example - we can't easily display all jobs(Launched event) for the particular Escrow Factory. All modern APIs can't handle more than 10k blocks per time. This is painful for any dashboard/telemetry application related to HUMAN

**Describe the solution you'd like**
Integrate the https://thegraph.com to the hmt-escrow. There is already a written [solution](https://github.com/humanprotocol/humansubgraph) here. Need to move code to this repo
Add clear instructions in the README section on how to use subgraphs. After each contract change trigger subgraphs recompilation via CI/CD mechanism(already in the [subgraph](https://github.com/humanprotocol/humansubgraph)) repo

**Additional context**
1. Ask @ivhus for helping with CI
2. Connected to #331 

**If you need help**
Join tech-discussions on the human protocol discord.

**Comment by foufrix** [comment]
Hi @vkomodey , this issue seems also to be linked to this one https://github.com/humanprotocol/humansubgraph/issues/7 no?

**Comment by vkomodey** [comment]
@foufrix that's right

**Comment by posix4e** [comment]
@foufrix i just talked to the team and I was totally wrong . It is open for @charlie

**Comment by foufrix** [comment]
Ok @Charlie85270 for you to catch up, @posix4e I'll delete my previous comment, and random charlie got pinged 😄

**Comment by ivhus** [comment]
@vkomodey @Charlie85270

As I understood you want to trigger ci+cd for subgraphs from the event in this repo.

This can be done cross-repo (triggered in https://github.com/humanprotocol/humansubgraph repo's CICD upon event in this repo), what the triggering event should be, a commit to `master` here?

But it won't deploy anything new there as subgraph didn't change. In other words, what is "subgraphs recompilation"?

**Comment by ivhus** [comment]
Now had a look at PR https://github.com/humanprotocol/hmt-escrow/pull/337

As I understood it's this ticket implemented, from CI+CD perspective looks fine @posix4e @vkomodey @charlie85270
