### ISSUE TITLE
Add CD instructions for redeploying all human subgraphs

### ISSUE THREAD

**Issue by vkomodey** [humanprotocol/hmt-escrow#344]
**Is your feature request related to a problem? Please describe.**

Problem: manual subgraph redeploy is required after each change in the hmt_subgrah folder.

**Describe the solution you'd like**
Redeploy subgraphs each time when either of "contracts" or "hmt_subgraph" folders have changes

**If you need help**
Join tech-discussions on the human protocol discord.

**Comment by foufrix** [comment]
Already fixed apparently by @posix4e

**Comment by vkomodey** [comment]
@foufrix how?

**Comment by posix4e** [comment]
Sorry I was confused. This isn’t fixed. It’s a documentation fix. let’s not
assign a bounty to it currently.
