### ISSUE TITLE
Query historical data from a GraphQL endpoint

### ISSUE THREAD

**Issue by ansaqib** [humanprotocol/hmt-escrow#352]
**Is your feature request related to a problem? Please describe.**
The current [dashboard](https://dashboard.humanprotocol.org/) implementation doesn't have historical data of the elements it reflects for respective networks.

**Describe the solution you'd like**
Query historical data (wrt time) from a GraphQL endpoint for the following elements:
- [ ] Amount Of Escrows
- [ ] All Escrows Pending Events
- [ ] All Escrows BulkTransfer Events
- [ ] All Escrows Intermediate Storage Events
- [ ] Total Number Of Escrow Events

for the following networks:
- [ ] Polygon Mainnet
- [ ] Polygon Mumbai Testnet
- [ ] Ethereum Rinkeby
- [ ] Neons Lab Devtestnet

also, query the following token data:
- [ ] Token Transfers
- [ ] Token Price
- [ ] Token Amount of transfers
- [ ] Token Holders

**Additional context**
Here is the UI/UX we need this data for
![Dashboard](https://user-images.githubusercontent.com/104921061/185634165-f183e1dc-eeae-4d58-86f6-8b18d6872db7.png)

**If you need help**
Join tech-discussions on the human protocol discord.

**Comment by Charlie85270** [comment]
Hello team, after discussed with foufrix on discord I'll work on this issue. 
This issue is for index and create GraphQL endpoint to query historical data (wrt time) ? 
Integrate the mock-up on the dashboard is another feature (Mock up is share to give context)  ?

**Comment by posix4e** [comment]
> Hello team, after discussed with foufrix on discord I'll work on this issue. 
> 
> This issue is for index and create GraphQL endpoint to query historical data (wrt time) ? 
> 

Yep!

> Integrate the mock-up on the dashboard is another feature (Mock up is share to give context)  ? 

Yep!

**Comment by foufrix** [comment]
PR linked to issue : https://github.com/humanprotocol/hmt-escrow/pull/357

**Comment by foufrix** [comment]
@Charlie85270 this is finished, right? From what I remember we have 2 points needed to be addressed on the dashboard

**Comment by foufrix** [comment]
PR linked to issue https://github.com/humanprotocol/escrow-dashboard/issues/70 (integration of price and token holder) the rest is done
