### ISSUE TITLE
Cleanup Docker, dependencies and testing

### ISSUE THREAD

**Issue by posix4e** [humanprotocol/hmt-escrow#390]
This repo has two major environments it runs under.

1) Python (legacy mode)
2) a more modern JS mode

Create two dockerfiles that all of the tests in the repo use which inherit the same root

## Make improvement ideas

- [x] All the contracts and abi generation can be centralized. We can remove duplicate abi copies copied and pasted throughout the repo.
- [x] The javascript version can take over all of the smart contract testing, hopefully in a single test run across every component (eth-kvstore, fortune, job launcher, escrow, token). It should also take over the smart contract linting, and we should upgrade the tools here. All of the contracts should be in one directory.  We shouldn't require docker for these tests and lints to be run directly from the github action.
- [x] The python container can be used just for the legacy python api only 
- [x] Docker will still be used for big end to end testing run

**Comment by posix4e** [comment]
@leric7 i'll be using your help to make sure we upgrade all the js/ethereum code to use a modern hard hat installlation

**Comment by portuu3** [comment]
Done in monorepo
