### ISSUE TITLE
bug: escrow-dashboard: amount Circulating Supply & Total Supply are wrong polygon tab

### ISSUE THREAD

**Issue by foufrix** [humanprotocol/hmt-escrow#412]
On the polygon tab here: https://dashboard.humanprotocol.org/
Circulating Supply (0) & Total Supply (1 000 000 000) are wrong, as total supply is the total token on both ETH & Polygon.
From the token contract on Polygon, we can see : https://polygonscan.com/token/0xc748b2a084f8efc47e086ccddd9b7e67aeb571bf that there are only 812,244 HMT bridged

![image](https://user-images.githubusercontent.com/16646581/198323905-44499cb6-6cae-4f6f-a4fe-a70433ea5b31.png)

Circulating Supply & Total supply are misleading, as they both represent the same thing.

**Comment by portuu3** [comment]
Fixed in monorepo
